
apiVersion: v1
kind: Service
metadata:
  name: {{ template "insightedge-manager.fullname" . }}-hs
  labels:
    app: {{ template "insightedge-manager.name" . }}
    chart: {{ template "insightedge-manager.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - name: zk-client
      port: {{ .Values.hs.zkClient }}
    - name: zk-server
      port: {{ .Values.hs.zkServer }}
    - name: zk-leader-election
      port: {{ .Values.hs.zkLeaderElection }}
    - name: lus
      port: {{ .Values.hs.lus }}
  clusterIP: None
  selector:
    selectorId: {{ template "insightedge-manager.fullname" . }}
