apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: insightedge-enterprise-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: insightedge-enterprise-operator
subjects:
  - kind: ServiceAccount
    name: insightedge-enterprise-operator
