apiVersion: apps/v1
kind: Deployment
metadata:
  name: insightedge-enterprise-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: insightedge-enterprise-operator
  template:
    metadata:
      labels:
        name: insightedge-enterprise-operator
    spec:
      serviceAccountName: insightedge-enterprise-operator
      containers:
        - name: insightedge-enterprise-operator
          # Replace this with the built image name
          image: quay.io/yoramw/insightedge-enterprise-operator:v0.0.3
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "insightedge-enterprise-operator"
            - name: RELATED_IMAGE_INSIGHTEDGE
              value: quay.io/yoramw/insightedge-enterprise:v15
